# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(040000)
$foreground = rgb(F1ECE3)
$color0 = rgb(080400)
$color1 = rgb(3F352C)
$color2 = rgb(453B32)
$color3 = rgb(6A6052)
$color4 = rgb(726656)
$color5 = rgb(9B917D)
$color6 = rgb(A29782)
$color7 = rgb(E3DBCE)
$color8 = rgb(9F9A90)
$color9 = rgb(54473B)
$color10 = rgb(5D4F42)
$color11 = rgb(8E806D)
$color12 = rgb(998872)
$color13 = rgb(CFC1A7)
$color14 = rgb(D7C9AE)
$color15 = rgb(E3DBCE)
